[build]
  publish = "."

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

# Optional: security headers
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
